config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  namespace :admin do
    resources :users
  end
  root to: 'tasks#index'
  resources :tasks do
    post :confirmation, action: :confirm_new, on: :new
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true, length: {maximum: 30}
  validate :validate_name_not_include_comma

  belongs_to :user

  scope :recent, -> {order(created_at: :desc)}

  private

  def validate_name_not_include_comma
    errors.add(:name, 'にカンマを含めることはできません') if name&.include?(',')
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :tasks
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: "ユーザー「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: "ユーザー「#{@user.name}」を更新しました。"
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url, notice: "ユーザー「#{@user.name}」を削除しました。"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def require_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :login_required

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_path unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'ログインしました'
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = current_user.tasks.order(created_at: :desc)
  end

  def show
  end

  def new
    @task = current_user.tasks.new
  end

  def confirm_new
    @task = current_user.tasks.new(task_params)
    render :new unless @task.valid?
  end

  def create
    @task = current_user.tasks.new(task_params)

    if params[:back].present?
      render :new
      return
    end

    if @task.save
      redirect_to @task, notice: "タスク「#{@task.name}」を登録しました。"
    else
      render :new
    end

  end

  def edit
  end

  def update
    @task.update!(task_params)
    redirect_to tasks_url, notice: "タスク「#{@task.name}」を更新しました。"
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, notice: "タスク「#{@task.name}」を削除しました。"
  end

  private

  def set_task
    @task = current_user.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :description)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/admin/users/_form.html.erb
<% if user.errors.present? %>
  <ul id="error_explanation">
    <% user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: [:admin, user], local: true do |f| %>
  <div class="form-group">
    <%= f.label :name, '名前' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email, 'メールアドレス' %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="form-check">
    <%= f.label :admin, class: 'form-check-label' do %>
      <%= f.check_box :admin, class: 'form-check-input' %>
      管理者権限
    <% end %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'パスワード' %>
    <%= f.text_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, 'パスワード（確認）' %>
    <%= f.text_field :password_confirmation, class: 'form-control' %>
  </div>
  <%= f.submit '登録する', class: 'btn btn-primary' %>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Admin::Users#edit</h1>

<div class="nav justify-content-end">
  <%= link_to '一覧', admin_users_path, class: 'nav-link' %>
</div>

<%= render partial: 'form', locals: { user: @user } %>

app/views/admin/users/index.html.erb
<h1>Admin::Users#index</h1>

<%= link_to '新規登録', new_admin_user_path, class: 'btn btn-primary' %>

<div class="mb-3">
  <table class="table table-hover">
    <thead class="thead-default">
      <tr>
        <th><%= User.human_attribute_name(:name) %></th>
        <th><%= User.human_attribute_name(:email) %></th>
        <th><%= User.human_attribute_name(:admin) %></th>
        <th><%= User.human_attribute_name(:created_at) %></th>
        <th><%= User.human_attribute_name(:updated_at) %></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.name, [:admin, user] %></td>
          <td><%= user.email %></td>
          <td><%= user.admin? ? 'あり':'なし' %></td>
          <td><%= user.created_at %></td>
          <td><%= user.updated_at %></td>
          <td>
            <%= link_to '編集', edit_admin_user_path(user), class: 'btn btn-primary mr-3' %>
            <%= link_to '削除', [:admin, user], method: :delete, data: { confirm: "ユーザー「#{user.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/users/new.html.erb
<h1>Admin::Users#new</h1>

<div class="nav justify-content-end">
  <%= link_to '一覧', admin_users_path, class: 'nav-link' %>
</div>

<%= render partial: 'form', locals: { user: @user } %>

app/views/admin/users/show.html.erb
<h1>Admin::Users#show</h1>

<div class="nav justify-content-end">
  <%= link_to '一覧', tasks_path, class: 'nav-link' %>
</div>

<table class="table table-hover">
  <tbody>
  <tr>
    <th><%= Task.human_attribute_name(:id) %></th>
    <td><%= @user.id %></td>
  </tr>
  <tr>
    <th><%= Task.human_attribute_name(:name) %></th>
    <td><%= @user.name %></td>
  </tr>
  <tr>
    <th><%= Task.human_attribute_name(:email) %></th>
    <td><%= @user.email %></td>
  </tr>
  <tr>
    <th><%= Task.human_attribute_name(:admin) %></th>
    <td><%= @user.admin? ? 'あり':'なし' %></td>
  </tr>
  <tr>
    <th><%= Task.human_attribute_name(:created_at) %></th>
    <td><%= @user.created_at %></td>
  </tr>
  <tr>
    <th><%= Task.human_attribute_name(:updated_at) %></th>
    <td><%= @user.updated_at %></td>
  </tr>
  </tbody>
</table>

<%= link_to '編集', edit_admin_user_path, class: 'btn btn-primary mr-3' %>
<%= link_to '削除', [:admin, @user], method: :delete, data: { confirm: "ユーザー「#{@user.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskleaf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="app-title navbar navbar-expand-md navbar-light bg-light">
      <div class="navbar-brand">Taskleaf</div>
      <ul class="navbar-nav ml-auto">
        <% if current_user %>
          <li class="nav-item">
            <%= link_to 'タスク一覧', tasks_path, class: 'nav-link' %>
          </li>
          <% if current_user.admin? %>
            <li class="nav-item">
              <%= link_to 'ユーザー一覧', admin_users_path, class: 'nav-link' %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'ログイン', login_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="container">
      <% if flash.notice.present? %>
        <div class="alert alert-success">
          <%= flash.notice %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<% if task.errors.present? %>
  <ul id="error_explanation">
    <% task.errors.full_messages.each do |mesage| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: task, local: true do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', id: 'task-name' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, rows: 5, class: 'form-control', id: 'task-description' %>
  </div>
  <%= f.submit nil, class: 'btn btn-primary' %>
<% end %>

app/views/tasks/confirm_new.html.erb
<h1>登録内容の確認</h1>

<%= form_with model: @task, local: true do |f| %>
  <table class="table table-hover">
    <tbody>
    <tr>
      <th>
        <%= Task.human_attribute_name(:name) %>
      </th>
      <td>
        <%= @task.name %>
      </td>
      <%= f.hidden_field :name %>
    </tr>
    <tr>
      <th>
        <%= Task.human_attribute_name(:description) %>
      </th>
      <td>
        <%= simple_format(@task.description) %>
      </td>
      <%= f.hidden_field :description %>
    </tr>
    </tbody>
  </table>
  <%= f.submit '戻る', name: 'back', class: "btn btn-secondary mr-3" %>
  <%= f.submit '登録', class: "btn btn-primary" %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>

<div class="nav justify-content-end">
  <%= link_to '一覧', tasks_path, class: 'nav-link' %>
</div>

<%= render partial: 'form', locals: { task: @task } %>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>

<%= link_to '新規登録', new_task_path, class: 'btn btn-primary' %>

<div class="mb-3">
  <table class="table table-hover">
    <thead class="thead-default">
      <tr>
        <th>
          <%= Task.human_attribute_name(:name) %>
        </th>
        <th>
          <%= Task.human_attribute_name(:created_at) %>
        </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= link_to task.name, task %></td>
          <td><%= task.created_at %></td>
          <td>
            <%= link_to '編集', edit_task_path(task), class: 'btn btn-primary mr-3' %>
            <%= link_to '削除', task, method: :delete, data: { confirm: "タスク「#{task.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>

<% if @task.errors.present? %>
  <ul id="error_explanation">
    <% @task.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @task, local: true , url: confirmation_new_task_path do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', id: 'task-name' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, rows: 5, class: 'form-control', id: 'task-description' %>
  </div>
  <%= f.submit nil, class: 'btn btn-primary' %>
<% end %>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>

<div class="nav justify-content-end">
  <%= link_to '一覧', tasks_path, class: 'nav-link' %>
</div>

<table class="table table-hover">
  <tbody>
    <tr>
      <th><%= Task.human_attribute_name(:id) %></th>
      <td><%= @task.id %></td>
    </tr>
    <tr>
      <th><%= Task.human_attribute_name(:name) %></th>
      <td><%= @task.name %></td>
    </tr>
    <tr>
      <th><%= Task.human_attribute_name(:description) %></th>
      <td><%= auto_link(simple_format(h(@task.description), {}, sanitize: false, wrapper_tag: 'div')) %></td>
    </tr>
    <tr>
      <th><%= Task.human_attribute_name(:created_at) %></th>
      <td><%= @task.created_at %></td>
    </tr>
    <tr>
      <th><%= Task.human_attribute_name(:updated_at) %></th>
      <td><%= @task.updated_at %></td>
    </tr>
  </tbody>
</table>

<%= link_to '編集', edit_task_path, class: 'btn btn-primary mr-3' %>
<%= link_to '削除', @task, method: :delete, data: { confirm: "タスク「#{@task.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger' %>